### ISSUE TITLE
blank page on first visit

### ISSUE THREAD

**Issue by ungoldman** [beakerbrowser/fritter#23]
Hello! 👋

I'm seeing a blank page on my first visit to dat://fritter.hashbase.io (using Beaker).

Here's the log:

```
index.js:2075 Rebuilding indexes.
index.js:2093 Database is opened.
index.js:25650 Uncaught (in promise) TypeError: Cannot read property 'url' of null
    at Object.render (index.js:25650)
    at FritterApp.render (index.js:1439)
    at FritterApp.setView (index.js:1374)
    at Function.router.on (index.js:1294)
    at emit (index.js:25200)
    at FritterApp.emit [as router] (index.js:16949)
    at onRouteChange (index.js:1299)
    at FritterApp.setup (index.js:1320)
    at <anonymous>
render @ index.js:25650
render @ index.js:1439
setView @ index.js:1374
router.on @ index.js:1294
emit @ index.js:25200
emit @ index.js:16949
onRouteChange @ index.js:1299
setup @ index.js:1320
index.js:1677 Uncaught (in promise) TypeError: Cannot read property 'followUrls' of null
    at whoToFollowSeedUrls.forEach.url (dat://fritter.hashbase.io/assets/index.js:1677:34)
    at Array.forEach (native)
    at FritterApp.loadWhoToFollow (dat://fritter.hashbase.io/assets/index.js:1676:25)
    at FritterApp.setup (dat://fritter.hashbase.io/assets/index.js:1330:10)
    at <anonymous>
whoToFollowSeedUrls.forEach.url @ index.js:1677
loadWhoToFollow @ index.js:1676
setup @ index.js:1330
```

**Comment by ungoldman** [comment]
@taravancil working now! Thanks.
